project_id = "the-grid"

[api]
enabled = true
schemas = ["public", "graphql_public"]

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
