import Link from "next/link";
import { deleteMaintenanceRecord, deleteMaintenanceRecordItem } from "@/app/actions";
import DeleteRecordButton from "../../DeleteRecordButton";

type ServiceItem = { id: string; category: string; title: string; details: string | null; quantity: string | null; line_amount: number | null; source_item_number: string | null; status: string; };
type ServiceRecord = { id: string; service_date: string; category: string; title: string; description: string | null; odometer_miles: number | null; vendor: string | null; cost: number | null; next_due_date: string | null; next_due_miles: number | null; source_url: string | null; source_reference?: string | null; source_file_name?: string | null; source_signed_url?: string | null; maintenance_record_items: ServiceItem[]; };

export default function ServiceRecords({ vehicleId, records }: { vehicleId: string; records: ServiceRecord[] }) {
  return <div className="service-records">{records.map((record) => <details className="service-record" key={record.id}>
    <summary className="service-record-summary"><div><time>{new Date(`${record.service_date}T12:00:00`).toLocaleDateString()}</time><h3>{record.title}</h3><p>{record.category}{record.vendor ? ` · ${record.vendor}` : ""}</p></div><div className="service-record-summary-meta"><span>{record.maintenance_record_items.length} items</span><strong>{record.cost != null ? `$${Number(record.cost).toFixed(2)}` : "—"}</strong><i aria-hidden="true">⌄</i></div></summary>
    <div className="service-record-body">
      <div className="service-record-toolbar"><div>{record.description && <p>{record.description}</p>}<span>{record.odometer_miles != null ? `${record.odometer_miles.toLocaleString()} miles` : "Mileage not recorded"}{record.source_reference ? ` · Reference ${record.source_reference}` : ""}{record.next_due_date ? ` · Next due ${new Date(`${record.next_due_date}T12:00:00`).toLocaleDateString()}` : ""}{record.next_due_miles != null ? ` · ${record.next_due_miles.toLocaleString()} miles` : ""}</span></div><div className="record-actions">{record.source_signed_url && <a className="button outline compact-button" href={record.source_signed_url} target="_blank" rel="noreferrer">View source</a>}<Link className="button outline compact-button" href={`/dashboard/vehicles/${vehicleId}/service/${record.id}/edit`}>Edit record</Link><DeleteRecordButton action={deleteMaintenanceRecord} fields={{ vehicle_id: vehicleId, maintenance_record_id: record.id }} confirmMessage={`Delete ${record.title} and all of its detailed service items?`} /></div></div>
      <div className="service-item-heading"><span>{record.maintenance_record_items.length} detailed items</span><Link className="button outline compact-button" href={`/dashboard/vehicles/${vehicleId}/service/${record.id}/items/new`}>Add item</Link></div>
      {record.maintenance_record_items.length ? <div className="service-item-list">{record.maintenance_record_items.map((item) => <div className="service-item" key={item.id}><div><small>{item.category}{item.source_item_number ? ` · ITEM ${item.source_item_number}` : ""}</small><strong>{item.title}</strong><span>{item.details || "No details"}</span><em>{[item.quantity, item.status].filter(Boolean).join(" · ")}</em></div><b>{item.line_amount != null ? `$${Number(item.line_amount).toFixed(2)}` : "—"}</b><div className="record-actions"><Link className="button outline compact-button" href={`/dashboard/vehicles/${vehicleId}/service/${record.id}/items/${item.id}/edit`}>Edit item</Link><DeleteRecordButton action={deleteMaintenanceRecordItem} fields={{ vehicle_id: vehicleId, maintenance_record_id: record.id, item_id: item.id }} confirmMessage={`Delete ${item.title}?`} /></div></div>)}</div> : <p className="service-no-items">No detailed items yet.</p>}
    </div>
  </details>)}</div>;
}
