"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Session = { id: string; session_number: number; started_at: string | null; best_lap_ms: number | null };
type Event = { id:string; business_id:string; event_date:string; event_name:string; track_name:string; configuration_name:string; status:string; vehicle_id:string|null; event_type_id:string|null; driver_name:string|null; temperature_f:number|null; conditions:string|null; wind_speed_mph:number|null; humidity_pct:number|null; track_condition:string|null; tire_set_id:string|null; front_pad_set_id:string|null; rear_pad_set_id:string|null; vehicles:{name:string}|null; sessions:Session[] };
type QualityIssue = { key:string; event:Event; level:"record"|"session"; title:string; detail:string; session?:Session };
type Review = { issue_key:string; resolution:"confirmed"|"intentionally_missing"; resolved_at:string };
const displayDate = (date:string) => new Date(`${date}T12:00:00`).toLocaleDateString("en-US", { month:"short", day:"numeric", year:"numeric" });

export default function DataQualityClient({ events, reviews, resolveAction, reopenAction }: { events:Event[]; reviews:Review[]; resolveAction:(formData:FormData)=>Promise<void>; reopenAction:(formData:FormData)=>Promise<void> }) {
  const [filter,setFilter]=useState("all"); const [status,setStatus]=useState<"open"|"resolved">("open");
  const issues = useMemo(() => {
    const result:QualityIssue[]=[];
    events.forEach((event) => {
      const add=(key:string,title:string,detail:string)=>result.push({key:`${event.id}-${key}`,event,level:"record",title,detail});
      if(!event.event_type_id)add("event-type","Missing Event Type","Assign a controlled Event Type."); if(!event.vehicle_id)add("vehicle","Missing vehicle","Assign the vehicle used for this event."); if(!event.driver_name?.trim())add("driver","Missing driver","Add the event driver.");
      if([event.temperature_f,event.conditions,event.wind_speed_mph,event.humidity_pct,event.track_condition].some(value=>value==null||value===""))add("weather","Incomplete weather","Review the event-level weather record.");
      if(!event.tire_set_id)add("tire","Missing tire assignment","Assign a tire set or confirm historical data is unavailable."); if(!event.front_pad_set_id)add("front-pad","Missing front pad assignment","Assign a front pad set or confirm historical data is unavailable."); if(!event.rear_pad_set_id)add("rear-pad","Missing rear pad assignment","Assign a rear pad set or confirm historical data is unavailable.");
      if(!event.sessions.length&&event.status==="complete")add("sessions","Completed event has no sessions","Add sessions or verify the event should remain empty.");
      event.sessions.forEach(session=>{if(session.best_lap_ms==null)result.push({key:`${session.id}-lap`,event,session,level:"session",title:"Missing lap time",detail:"Add the lap or confirm timing was not provided."});if(session.started_at==null)result.push({key:`${session.id}-start`,event,session,level:"session",title:"Missing start time",detail:"Add the session start time or confirm it is unknown."});});
    });
    const groups=new Map<string,Event[]>(); events.forEach(event=>{const key=[event.event_date,event.track_name,event.configuration_name,event.vehicle_id??""].join("|");groups.set(key,[...(groups.get(key)??[]),event]);}); groups.forEach(group=>{if(group.length>1)group.forEach(event=>result.push({key:`${event.id}-duplicate`,event,level:"record",title:"Possible duplicate event",detail:`${group.length} events share this date, vehicle, track, and configuration. Review before changing.`}));}); return result;
  },[events]);
  const reviewMap=new Map(reviews.map(review=>[review.issue_key,review])); const openCount=issues.filter(issue=>!reviewMap.has(issue.key)).length; const issueTypes=[...new Set(issues.map(issue=>issue.title))].sort(); const visible=issues.filter(issue=>(status==="resolved")===reviewMap.has(issue.key)&&(filter==="all"||issue.title===filter));
  return <><section className="data-management-summary"><div className={openCount?"warning":"good"}><strong>{openCount}</strong><span>Open issues</span></div><div><strong>{reviews.length}</strong><span>Resolved</span></div><div><strong>{events.length}</strong><span>Events scanned</span></div><div><strong>{issues.length}</strong><span>Total findings</span></div></section><section className="section-block"><div className="quality-status-tabs"><button className={status==="open"?"active":""} onClick={()=>setStatus("open")}>Open <span>{openCount}</span></button><button className={status==="resolved"?"active":""} onClick={()=>setStatus("resolved")}>Resolved <span>{reviews.length}</span></button></div><div className="quality-toolbar"><label>Issue type<select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All issues</option>{issueTypes.map(name=><option key={name}>{name}</option>)}</select></label><span>Showing <strong>{visible.length}</strong> records</span></div><div className="quality-list">{visible.map(issue=>{const review=reviewMap.get(issue.key);return <div className="quality-card" key={issue.key}><div><span className="quality-type">{issue.level}</span><strong>{issue.title}</strong><p>{issue.detail}</p><small>{issue.event.business_id} · {displayDate(issue.event.event_date)} · {issue.event.vehicles?.name??"Unassigned"}{issue.session?` · Session ${issue.session.session_number}`:""}{review?` · ${review.resolution.replace("_"," ")}`:""}</small></div><div className="quality-actions"><Link className="button ghost small" href={issue.session?`/dashboard/events/${issue.event.id}/sessions/${issue.session.id}/edit`:`/dashboard/events/${issue.event.id}/edit`}>Fix record</Link>{review?<form action={reopenAction}><input type="hidden" name="issue_key" value={issue.key}/><button className="text-button">Reopen</button></form>:<><Decision action={resolveAction} issue={issue} resolution="confirmed" label="Confirm"/><Decision action={resolveAction} issue={issue} resolution="intentionally_missing" label="Unavailable"/></>}</div></div>})}</div>{!visible.length&&<div className="empty-state compact"><strong>No matching issues.</strong><p>Nothing in this view needs attention.</p></div>}</section></>;
}
function Decision({action,issue,resolution,label}:{action:(formData:FormData)=>Promise<void>;issue:QualityIssue;resolution:"confirmed"|"intentionally_missing";label:string}){return <form action={action}><input type="hidden" name="issue_key" value={issue.key}/><input type="hidden" name="issue_type" value={issue.title}/><input type="hidden" name="entity_type" value={issue.session?"session":"event"}/><input type="hidden" name="entity_id" value={issue.session?.id??issue.event.id}/><input type="hidden" name="resolution" value={resolution}/><button className="text-button">{label}</button></form>}
